package com.example.simon.tripbuddy_v0;

import java.util.ArrayList;


public class MyRessources extends ArrayList<Lieux> {
    public MyRessources() {
        super();
        this.add(new Lieux(R.drawable.arc_de_triomphe, 0, "Arc de triomphe", "L’arc de triomphe de l’Étoile souvent appelé simplement l'Arc de Triomphe, dont la construction, décidée par l'empereur Napoléon Ier, débuta en 1806 et s'acheva en 1836 sous Louis-Philippe, est situé à Paris, dans le 8e arrondissement. Il s'élève au centre de la place Charles-de-Gaulle (anciennement place de l’Étoile), dans l'axe et à l’extrémité ouest de l’avenue des Champs-Élysées, à 2,2 kilomètres de la place de la Concorde. Haut de 49,54 m, large de 44,82 m et profond de 22,21 m, il est géré par le Centre des monuments nationaux. La hauteur de la grande voûte est de 29,19 m et sa largeur de 14,62 m. La petite voûte mesure 18,68 m de haut et 8,44 m de large. Le monument pèse 50 000 t, 100 000 t en prenant en compte les fondations qui s'enfoncent à 8,37 m de profondeur. Le coût total de la construction est de 9 651 116 F."));
        this.add(new Lieux(R.drawable.concorde, 0, "Concorde", "Située sur la Rive droite, dans le 8e arrondissement, au pied des Champs-Élysées, elle relie ceux-ci, qui montent vers le nord-ouest, aux jardin des Tuileries qui s'étendent vers le sud-est. Par la rue Royale, elle ouvre au nord sur la Madeleine et au sud, par le pont de la Concorde qui traverse la Seine vers le 7e arrondissement, sur le palais Bourbon. Administrativement, la place elle-même est située dans le quartier des Champs-Élysées, dont elle est l’extrémité orientale. Mais les deux bâtiments qui la bordent au nord, de part et d’autre de la rue Royale, sont dans le quartier de la Madeleine, toujours dans le 8e arrondissement, tandis que le jardin des Tuileries qui la jouxte est situé dans le quartier Saint-Germain-l'Auxerrois du 1re arrondissement."));
        this.add(new Lieux(R.drawable.eiffel_tower, 0, "Tour Eiffel", "La tour Eiffel (Prononciation du titre dans sa version originale Écouter) est une tour de fer puddlé de 324 mètres de hauteur (avec antennes) située à Paris, à l’extrémité nord-ouest du parc du Champ-de-Mars en bordure de la Seine dans le 7e arrondissement. Construite par Gustave Eiffel et ses collaborateurs pour l’Exposition universelle de Paris de 1889, et initialement nommée « tour de 300 mètres », ce monument est devenu le symbole de la capitale française, et un site touristique de premier plan : il s’agit du second site culturel français payant le plus visité en 2011, avec 7,1 millions de visiteurs dont 75 % d'étrangers en 2011, la cathédrale Notre-Dame de Paris étant en tête des monuments à l'accès libre avec 13,6 millions de visiteurs estimés mais il reste le monument payant le plus visité au monde. Elle a accueilli son 250 millionième visiteur en 2010."));
        this.add(new Lieux(R.drawable.louvre, 0, "Musée du Louvre", "Le musée du Louvre est un musée d'art et d'antiquités situé au centre de Paris dans le palais du Louvre. C'est l'un des plus grands musées du monde, et le plus grand de Paris, par sa surface d'exposition de 60 600 m27, et ses collections qui comprennent près de 460 000 œuvres. Celles-ci présentent l'art occidental du Moyen Âge à 1848, ceux des civilisations antiques qui l'ont précédé et influencé (orientales, égyptienne, grecque, étrusque et romaine), et les arts des premiers chrétiens et de l\'Islam.\nSitué dans le 1er arrondissement de Paris, entre la rive droite de la Seine et la rue de Rivoli, le musée se signale par la pyramide de verre de son hall d\'accueil, érigée en 1989 dans la cour Napoléon et qui en est devenue emblématique ; tandis que la statue équestre de Louis XIV constitue le point de départ de l'axe historique parisien. Avec environ neuf millions de visiteurs annuels (depuis 2011), le Louvre est le musée le plus visité au monde, et le site culturel payant le plus visité de France. Parmi ses pièces les plus célèbres figurent La Joconde, la Vénus de Milo, Le Scribe accroupi et le Code de Hammurabi."));
        this.add(new Lieux(R.drawable.montmartre, 0, "Montmartre", "Montmartre est un quartier du nord de Paris couvrant la colline de la butte Montmartre, qui est l'un des principaux lieux touristiques parisiens. C'est à Montmartre qu'est situé le point culminant de la capitale : 130,53 mètres, altitude du sol naturel à l’intérieur du cimetière du Calvaire, qui jouxte l’église Saint-Pierre de Montmartre.\\n\\nJusqu'à son annexion par Paris en 1860, Montmartre était une commune française du département de la Seine, à la superficie plus étendue que le quartier actuel. L'essentiel de son territoire constitue depuis lors les quartiers administratifs des Grandes-Carrières et de Clignancourt, dans le 18e arrondissement de la capitale, dit « quartier de la butte-Montmartre », et une fraction fut attribuée à la commune de Saint-Ouen.\\n\\nLes deux accès les plus connus pour le sommet de la colline sont le funiculaire ou la rue Foyatier, un escalier de 222 marches avec paliers le longeant."));
        this.add(new Lieux(R.drawable.notre_dame, 0, "Notre Dame de Paris", "La cathédrale Notre-Dame de Paris, en forme courte Notre-Dame, est la cathédrale de l’archidiocèse de Paris, en France. Elle est située dans l'Est de l’île de la Cité, dans le 4e arrondissement de Paris. Sa façade occidentale domine le parvis Notre-Dame - place Jean-Paul-II.\\n\\nLa construction de la cathédrale, lancée sous l'impulsion de l’évêque Maurice de Sully, s'est étendue sur plus de deux siècles, de 1163 au milieu du xive siècle. Le style n’est donc pas d’une uniformité totale : elle possède ainsi des caractères du gothique primitif (voûtes sexpartites de la nef) et du gothique rayonnant. Les deux rosaces qui ornent chacun des bras du transept sont parmi les plus grandes d’Europe, et mesurent chacune 13 mètres de diamètre. Elle fut lors de son achèvement l'une des plus grandes cathédrales d'Occident. Après la tourmente révolutionnaire, la cathédrale a subi de 1844 à 1864 une restauration importante et parfois controversée dirigée par l’architecte Viollet-le-Duc, qui y a incorporé des éléments et des motifs inédits.\\n\\nLa cathédrale est depuis sa construction un des monuments les plus emblématiques de Paris. Longtemps plus haute construction de la ville, elle tient une place symbolique de premier rang dans son image. À la fois édifice religieux et culturel, elle a souvent été au cœur de l’histoire de France. Paroisse royale au Moyen Âge, c’est dans la cathédrale que s’est notamment déroulé l’arrivée de la Sainte Couronne en 1239, le sacre de Napoléon Ier en 1804, les funérailles d’Adolphe Thiers, Sadi Carnot ou encore le Te Deum célébré à la libération de Paris en 1944. Une cérémonie religieuse officielle eut lieu le 11 janvier 1996, à l'occasion du décès de François Mitterrand.\\n\\nL'église accueille aujourd’hui plus de vingt millions de visiteurs par an (dont quatorze qui entrent dans la cathédrale), ce qui en fait le monument le plus visité de Paris et de toute l’Europe. Bénéficiant d'un dynamisme nouveau et vivace, elle a fêté en 2013 le 850e anniversaire de sa construction."));
        this.add(new Lieux(R.drawable.orsay, 0, "Musée d'Orsay", "Orsay est une commune française située à vingt-deux kilomètres au sud-ouest de Paris dans le département de l’Essonne en région Île-de-France. Elle est le chef-lieu de l'ancien canton d'Orsay et abrite le siège de la communauté d'agglomération Communauté Paris-Saclay.\\n\\nPlace forte de la vallée de Chevreuse dès le viiie siècle, village agricole possession de personnages influents et généreux, Orsay se développa dès le xixe siècle avec l’arrivée du chemin de fer et de donateurs qui permirent l’édification d’un centre hospitalier encore en activité aujourd’hui. Siège de l’université Paris-Sud 11, la commune est devenue une cité pavillonnaire de l’agglomération parisienne facilement accessible, à l’environnement préservé au cœur du pôle scientifique Paris-Saclay, avec sur son territoire des laboratoires du CNRS et de l’Institut Curie."));
        this.add(new Lieux(R.drawable.saintmartin, 0, "Canal saint Martin", "Le canal Saint-Martin est un canal de 4,55 km de long situé essentiellement dans les 10e et 11e arrondissements de Paris. Il relie le bassin de la Villette — et au-delà le canal de l'Ourcq — au port de l'Arsenal (le port de plaisance de Paris) qui communique avec la Seine. C'est un canal de petit gabarit destiné, à l'origine, à l'adduction d'eau potable dans la capitale. Inauguré en 1825, il comporte neuf écluses et deux ponts tournants pour une dénivellation totale de 25 m.\\n\\nAvec le canal de l'Ourcq, le bassin de la Villette et le canal Saint-Denis, il constitue le réseau des canaux parisiens, long de 130 km, qui appartient à la Ville de Paris. Le canal Saint-Martin est inscrit monument historique depuis le 23 février 1993."));
        this.add(new Lieux(R.drawable.versailles, 0, "Chateau de Versailles", "Le château de Versailles est un château et un monument historique français qui se situe à Versailles, dans les Yvelines, en France. Il fut la résidence des rois de France Louis XIV, Louis XV et Louis XVI. Le roi et la cour y résidèrent de façon permanente du 6 mai 1682 au 6 octobre 1789, à l'exception des années de la Régence de 1715 à 1723.\nBuste de Louis XIV par Gian Lorenzo Bernini dans le château de Versailles.\nSitués au Sud-Ouest de Paris, ce château et son domaine visaient à glorifier la monarchie française.\n\nLe château est constitué d'une succession d'éléments ayant une harmonie architecturale. Il s'étale sur 63 154 m², répartis en 2 300 pièces, dont, actuellement, 1 000 pièces de musée1.\n\nLe parc du château de Versailles s'étend sur 815 ha, contre environ 8 000 ha avant la Révolution françaisenote 1, dont 93 ha de jardins. Il comprend de nombreux éléments, dont le Petit et le Grand Trianon (qui fut également résidence de Napoléon Ier, Louis XVIII, Charles X, Louis-Philippe Ier, et Napoléon III), le hameau de la Reine, le Grand et le Petit Canal, une ménagerie (aujourd’hui détruite), une orangerie et la pièce d'eau des Suisses."));
        for(int i = 0; i < this.size(); i++){
            this.get(i).setResourceId(i);
        }
    }



}
